stages:
  - buildstack

before_script:
  - mkdir build
  - mkdir install

after_script:
  - sudo chown -R gitlab-runner:gitlab-runner .

build_stack:
  stage: buildstack
  script:
    - sudo ./configure --prefix ~/install
    - sudo make install
